stages:
  - Install
  - Build
  - Deploy

.install_template: &install_definition
  stage: Install
  cache:
    paths:
      - node_modules/
  script:
    - npm install --legacy-peer-deps

.build_template: &build_definition
  stage: Build
  cache:
    paths:
      - node_modules/
  script:
    - echo $REACT_APP_ENV
    - REACT_APP_PUBLIC_URL=$REACT_APP_PUBLIC_URL REACT_APP_ENV=$REACT_APP_ENV npm run build
    - echo "$HTACCESS" > build/.htaccess
  artifacts:
    paths:
      - build

# Dev environment
InstallDev:
  <<: *install_definition
  environment:
    name: dev
  only:
    - develop@lnd-training/hb-future-01/mock-project/hb-request-gate-group-1/frontend

BuildDev:
  <<: *build_definition
  environment:
    name: dev
  variables:
    REACT_APP_ENV: dev
  only:
    - develop@lnd-training/hb-future-01/mock-project/hb-request-gate-group-1/frontend

DeployDev:
  stage: Deploy
  image: node:8.14.0-alpine
  only:
    - develop@lnd-training/hb-future-01/mock-project/hb-request-gate-group-1/frontend
  environment:
    name: dev
  script:
    - apk add rsync && apk add openssh
    - eval $(ssh-agent -s) && echo "$DEPLOY_SSH_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\tControlMaster auto\n\tControlPath /tmp/ansible-%r@%h:%p\n\tControlPersist 15m\n\tPreferredAuthentications publickey
  \n\n" > ~/.ssh/config'
    - chmod go-wrx -R ~/.ssh
    - echo "OK" >public/health.html && rsync -azP --exclude='.git*' --exclude=node_modules/ build/ $DEV_DEPLOY_USER@$DEV_DEPLOY_HOST:$DEV_DEPLOY_DIR/
    - ssh $DEV_DEPLOY_USER@$DEV_DEPLOY_HOST "aws s3 sync $DEV_DEPLOY_DIR/ s3://$DEV_S3_BUCKET/"
    - ssh $DEV_DEPLOY_USER@$DEV_DEPLOY_HOST "aws cloudfront create-invalidation --distribution-id $DEV_CLOUDFRONT_ID --paths '/*'"

# Production environment
InstallProduction:
  <<: *install_definition
  environment:
    name: production
  only:
    - master@lnd-training/hb-future-01/mock-project/hb-request-gate-group-1/frontend

BuildProduction:
  <<: *build_definition
  environment:
    name: production
  variables:
    REACT_APP_ENV: production
  only:
    - master@lnd-training/hb-future-01/mock-project/hb-request-gate-group-1/frontend

DeployProduction:
  stage: Deploy
  image: node:8.14.0-alpine
  when: manual
  only:
    - master@lnd-training/hb-future-01/mock-project/hb-request-gate-group-1/frontend
  environment:
    name: production
  script:
    - apk add rsync && apk add openssh
    - eval $(ssh-agent -s) && echo "$DEPLOY_SSH_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\tControlMaster auto\n\tControlPath /tmp/ansible-%r@%h:%p\n\tControlPersist 15m\n\tPreferredAuthentications publickey
  \n\n" > ~/.ssh/config'
    - chmod go-wrx -R ~/.ssh
    - echo "OK" >public/health.html && rsync -azP --exclude='.git*' --exclude=node_modules/ build/ $PRO_DEPLOY_USER@$PRO_DEPLOY_HOST:$PRO_DEPLOY_DIR/
    - ssh $PRO_DEPLOY_USER@$PRO_DEPLOY_HOST "aws s3 sync $PRO_DEPLOY_DIR/ s3://$PRO_S3_BUCKET/"
    - ssh $PRO_DEPLOY_USER@$PRO_DEPLOY_HOST "aws cloudfront create-invalidation --distribution-id $PRO_CLOUDFRONT_ID --paths '/*'"
